version: '2'

services:
    commander:
        image: node:4
        volumes:
            - ../commander_vs_yargs/commander/:/data:ro
            - ../bench/:/bench:ro
            - ../results/:/results:rw
        command: ["./bench/install_then_run_no_progress.sh", "-n", "1000", "-o", "commander-bench", "-c", "commander-bench add -s 10 1 3 5 7 11"]

    yargs:
        image: node:4
        volumes:
            - ../commander_vs_yargs/yargs/:/data:ro
            - ../bench/:/bench:ro
            - ../results/:/results:rw
        command: ["./bench/install_then_run_no_progress.sh", "-n", "1000", "-o", "yargs-bench", "-c", "yargs-bench add -s 10 1 3 5 7 11"]